CREATE TABLE IF NOT EXISTS DESPESA(
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150) NOT NULL,
	VALOR double precision NOT NULL,
	MES_ANO_REFERENCIA date NOT NULL,	
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_DESPESA_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS RECEITA(
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150) NOT NULL,
	VALOR double precision NOT NULL,
	MES_ANO_REFERENCIA date NOT NULL,	
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_RECEITA_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);
