CREATE TABLE IF NOT EXISTS VISITANTE(
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150) NOT NULL,
	RG BIGINT,
	CPF BIGINT,
	TELEFONE BIGINT,	
	CONSTRAINT UQ_VISITANTE_RG_CONDOMINIO UNIQUE (RG),
	CONSTRAINT UQ_VISITANTE_CPF_CONDOMINIO UNIQUE (CPF),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS VISITA(
	ID integer NOT NULL AUTO_INCREMENT,	
	DATA_INICIO DATETIME NOT NULL,
	DATA_FIM DATETIME,
	PRESTAR_SERVICO boolean NOT NULL,	
	ID_CONDOMINIO integer NOT NULL,
	ID_BLOCO integer,
	ID_UNIDADE integer,
	ID_CONDOMINO integer,
	ID_VISITANTE integer NOT NULL,
	CONSTRAINT FK_VISITA_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_VISITA_ID_BLOCO_BLOCO_ID FOREIGN KEY (ID_BLOCO) REFERENCES BLOCO(ID),
	CONSTRAINT FK_VISITA_ID_UNIDADE_UNIDADE_ID FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	CONSTRAINT FK_VISITA_ID_CONDOMINO_CONDOMINO_ID FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),
	CONSTRAINT FK_VISITA_ID_VISITANTE_VISITANTE_ID FOREIGN KEY (ID_VISITANTE) REFERENCES VISITANTE(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS PRESTADOR_SERVICO(
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150) NOT NULL,
	TELEFONE BIGINT NOT NULL,
	CNPJ BIGINT,
	EMAIL varchar(150)	
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS VISITA_PRESTADOR_SERVICO(
	ID integer NOT NULL AUTO_INCREMENT,	
	ID_VISITA integer NOT NULL,
	ID_PRESTADOR_SERVICO integer NOT NULL,
	CONSTRAINT UQ_VISITA_PRESTADOR_SERVICO_ID_VISITA UNIQUE (ID_VISITA),	
	CONSTRAINT FK_VISITA_PRESTADOR_SERVICO_ID_VISITA_VISITA_ID FOREIGN KEY (ID_VISITA) REFERENCES VISITA(ID),
	CONSTRAINT FK_VISITA_PRESTADOR_SERVICO_ID_PREST_SERVICO_PREST_SERVICO_ID FOREIGN KEY (ID_PRESTADOR_SERVICO) REFERENCES PRESTADOR_SERVICO(ID),
	PRIMARY KEY(ID)
);S
