CREATE TABLE IF NOT EXISTS CONTADOR(
	ID integer NOT NULL AUTO_INCREMENT,	
	SITE varchar(150) NULL,
	TELEFONE_COMERCIAL bigint,
	TELEFONE_CELULAR1 bigint,
	TELEFONE_CELULAR2 bigint,
	TELEFONE_CELULAR3 bigint,
	CONSTRAINT FK_CONTADOR_ID_USUARIO_ID FOREIGN KEY (ID) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
);