ALTER TABLE GRUPO_USUARIO ADD COLUMN DESCRICAO VARCHAR(150) NULL DEFAULT '';

ALTER TABLE GRUPO_USUARIO ADD COLUMN SITUACAO BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE GRUPO_USUARIO ADD COLUMN ID_CONDOMINIO INTEGER NULL;

ALTER TABLE GRUPO_USUARIO ADD COLUMN ID_SINDICO_PROFISSIONAL INTEGER NULL;

ALTER TABLE GRUPO_USUARIO ADD COLUMN ID_ESCRITORIO_CONTABILIDADE INTEGER NULL;

ALTER TABLE GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_USUARIO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID);

ALTER TABLE GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_USUARIO_ID_SINDICO_PROFISSIONAL_SINDICO_PROFISSIONAL_ID FOREIGN KEY (ID_SINDICO_PROFISSIONAL) REFERENCES SINDICO_PROFISSIONAL(ID);

ALTER TABLE GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_USUARIO_ID_ESCRITORIO_CONTABILI_ESCRITORIO_CONTABILI_ID FOREIGN KEY (ID_ESCRITORIO_CONTABILIDADE) REFERENCES ESCRITORIO_CONTABILIDADE(ID);


CREATE TABLE IF NOT EXISTS TELA(
	ID integer NOT NULL AUTO_INCREMENT,	 
	NOME VARCHAR(150) NOT NULL,
	DESCRICAO VARCHAR(150) NOT NULL,
	NOME_ARQUIVO VARCHAR(150) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ABA(
	ID integer NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(150) NOT NULL,
	DESCRICAO VARCHAR(150) NOT NULL,
	ID_ABA VARCHAR(150) NOT NULL,
	ID_TELA integer NOT NULL,
	CONSTRAINT FK_ABA_ID_TELA_TELA_ID FOREIGN KEY (ID_TELA) REFERENCES TELA(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS GRUPO_USUARIO_TELA(
	ID integer NOT NULL AUTO_INCREMENT,
	ID_GRUPO_USUARIO integer NOT NULL, 
	ID_TELA integer NOT NULL,
	ACAO VARCHAR(100) NOT NULL,
	CONSTRAINT FK_GRUPO_USUARIO_TELA_ID_GRUPO_USUARIO_GRUPO_USUARIO_ID FOREIGN KEY (ID_GRUPO_USUARIO) REFERENCES GRUPO_USUARIO(ID),
	CONSTRAINT FK_GRUPO_USUARIO_TELA_ID_TELA_TELA_ID FOREIGN KEY (ID_TELA) REFERENCES TELA(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TELA_ABA_TELA(
	ID integer NOT NULL AUTO_INCREMENT,
	ID_TELA integer NOT NULL,
	ID_ABA_TELA integer NOT NULL,
	ACAO VARCHAR(100) NOT NULL,
	CONSTRAINT FK_TELA_ABA_TELA_ID_TELA_TELA_ID FOREIGN KEY (ID_TELA) REFERENCES TELA(ID),
	CONSTRAINT FK_TELA_ABA_TELA_ID_ABA_TELA_ABA_ID FOREIGN KEY (ID_ABA_TELA) REFERENCES ABA(ID),
	PRIMARY KEY(ID)
);

INSERT INTO TELA VALUES(DEFAULT,'formAnexaDocumento','formAnexoDocumentoDescricao','formAnexaDocumento.xhtml'),
(DEFAULT,'formAnexaImagem','formAnexaImagemDescricao','formAnexaImagem.xhtml'),
(DEFAULT,'formAprovaAgendamento','formAprovaAgendamentoDescricao','formAprovaAgendamento.xhtml'),
(DEFAULT,'formAprovaReserva','formAprovaReservaDescricao','formAprovaReserva.xhtml'),
(DEFAULT,'formCadastroAgendamento','formCadastroAgendamentoDescricao','formCadastroAgendamento.xhtml'),
(DEFAULT,'formCadastroAmbienteCondominio','formCadastroAmbienteCondominioDescricao','formCadastroAmbienteCondominio.xhtml'),
(DEFAULT,'formCadastroBeneficiario','formCadastroBeneficiarioDescricao','formCadastroBeneficiario.xhtml'),
(DEFAULT,'formCadastroBloco','formCadastroBlocoDescricao','formCadastroBloco.xhtml'),
(DEFAULT,'formCadastroChamado','formCadastroChamadoDescricao','formCadastroChamado.xhtml'),
(DEFAULT,'formCadastroClassificados','formCadastroClassificadosDescricao','formCadastroClassificados.xhtml'),
(DEFAULT,'formMeuPainel','formMeuPainelDescricao','formMeuPainel.xhtml');

INSERT INTO ABA VALUES(DEFAULT,'formMeuPainel.idTabDadosPessoais','formMeuPainel.idTabDadosPessoais.descricao','idTabDadosPessoais',11),
(DEFAULT,'formMeuPainel.idTabAlterarImagemCondomino','formMeuPainel.idTabAlterarImagemCondomino.descricao','idTabAlterarImagemCondomino',11);



