CREATE TABLE IF NOT EXISTS TIPO_CHAMADO(
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(50) NOT NULL,
	POSICAO integer NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CHAMADO(
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(50) NOT NULL,
	DESCRICAO varchar(250),
	STATUS integer NOT NULL,
	DATA_ABERTURA DATETIME NOT NULL,
	DATA_FECHAMENTO DATETIME,
	OUTROS varchar(100),
	ID_TIPO_CHAMADO integer,
	ID_CONDOMINIO integer NOT NULL,
	ID_USUARIO integer NOT NULL,
	CONSTRAINT FK_CHAMADO_ID_TIPO_CHAMADO_TIPO_CHAMADO_ID FOREIGN KEY (ID_TIPO_CHAMADO) REFERENCES TIPO_CHAMADO(ID),
	CONSTRAINT FK_CHAMADO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_CHAMADO_ID_ID_USUARIO_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
);

INSERT INTO TIPO_CHAMADO (NOME,POSICAO) VALUES  
('tipoChamado.barulhoVizinho',1),
('tipoChamado.lampadaQueimada',2),
('tipoChamado.outros',3);
