CREATE TABLE IF NOT EXISTS SINDICO_PROFISSIONAL(
	ID integer NOT NULL AUTO_INCREMENT,	
	SITE varchar(150) NULL,
	TELEFONE_COMERCIAL bigint,
	TELEFONE_CELULAR1 bigint,
	TELEFONE_CELULAR2 bigint,
	TELEFONE_CELULAR3 bigint,
	CONSTRAINT FK_SINDICO_PROFISSIONAL_ID_USUARIO_ID FOREIGN KEY (ID) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
);


ALTER TABLE GESTOR_CONDOMINIO DROP FOREIGN KEY FK_GESTOR_CONDOMINIO_ID_CONDOMINO_CONDOMINO_ID;
ALTER TABLE GESTOR_CONDOMINIO DROP KEY FK_GESTOR_CONDOMINIO_ID_CONDOMINO_CONDOMINO_ID;
ALTER TABLE GESTOR_CONDOMINIO CHANGE ID_CONDOMINO ID_USUARIO integer NOT NULL;
ALTER TABLE GESTOR_CONDOMINIO ADD CONSTRAINT FK_GESTOR_CONDOMINIO_ID_USUARIO_USUARIO_ID FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID);