CREATE TABLE IF NOT EXISTS AGENDAMENTO(
	ID integer NOT NULL AUTO_INCREMENT,
	DATA date NOT NULL,
	HORA_INICIAL varchar(10) NOT NULL,
	HORA_FINAL varchar(10) NOT NULL,
	OBSERVACAO varchar(200),
	SITUACAO varchar(30) NOT NULL,
	MOTIVO_REPROVACAO varchar(150),
	ID_CONDOMINO integer NOT NULL,
	CONSTRAINT FK_AGENDAMENTO_ID_CONDOMINO_CONDOMINO_ID FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),	
	PRIMARY KEY(ID)
);
