CREATE TABLE IF NOT EXISTS OBRA(
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150) NOT NULL,
	TIPO integer NOT NULL,
	SITUACAO integer NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE,
	DESCRICAO varchar(250),
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_OBRA_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL_OBRA(
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150),
	RAZAO_SOCIAL varchar(150),
	TIPO_PESSOA integer NOT NULL,
	TELEFONE BIGINT NOT NULL,	
	CPF BIGINT,
	CNPJ BIGINT,
	EMAIL varchar(150),
	SITE varchar(150),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS OBRA_RESPONSAVEL_OBRA(
	ID integer NOT NULL AUTO_INCREMENT,	
	ID_OBRA integer NOT NULL,
	ID_RESPONSAVEL_OBRA integer NOT NULL,
	CONSTRAINT UQ_OBRA_RESPONSAVEL_OBRA_ID_OBRA UNIQUE (ID_OBRA),	
	CONSTRAINT FK_OBRA_RESPONSAVEL_OBRA_ID_OBRA_OBRA_ID FOREIGN KEY (ID_OBRA) REFERENCES OBRA(ID),
	CONSTRAINT FK_OBRA_RESPONSAVEL_OBRA_ID_RESPONSAVEL_OBRA_RESPONSAVEL_OBRA_ID FOREIGN KEY (ID_RESPONSAVEL_OBRA) REFERENCES RESPONSAVEL_OBRA(ID),
	PRIMARY KEY(ID)
);