ALTER TABLE GRUPO_USUARIO ADD COLUMN DESCRICAO VARCHAR(150) NULL;

ALTER TABLE GRUPO_USUARIO ADD COLUMN ATIVO BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE GRUPO_USUARIO ADD COLUMN ID_CONDOMINIO INTEGER NULL;

ALTER TABLE GRUPO_USUARIO ADD COLUMN ID_SINDICO_PROFISSIONAL INTEGER NULL;

ALTER TABLE GRUPO_USUARIO ADD COLUMN ID_ESCRITORIO_CONTABILIDADE INTEGER NULL;

ALTER TABLE GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_USUARIO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID);

ALTER TABLE GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_USUARIO_ID_SINDICO_PROFISSIONAL_SINDICO_PROFISSIONAL_ID FOREIGN KEY (ID_SINDICO_PROFISSIONAL) REFERENCES SINDICO_PROFISSIONAL(ID);

ALTER TABLE GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_USUARIO_ID_ESCRITORIO_CONTABILIDADE_ESCRITORIO_CONTABILIDADE_ID FOREIGN KEY (ID_ESCRITORIO_CONTABILIDADE) REFERENCES ESCRITORIO_CONTABILIDADE(ID);