CREATE TABLE IF NOT EXISTS ESCRITORIO_CONTABILIDADE(
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(100) NOT NULL,
	SITE varchar(150) NULL,
	TELEFONE_COMERCIAL bigint NULL,
	TELEFONE_CELULAR bigint NULL,
	CNPJ BIGINT NOT NULL,
	SITUACAO integer NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CONTADOR(
	ID integer NOT NULL AUTO_INCREMENT,
	ID_ESCRITORIO_CONTABILIDADE integer NOT NULL, 
	CONSTRAINT FK_CONTADOR_ID_USUARIO_ID FOREIGN KEY (ID) REFERENCES USUARIO(ID),
	CONSTRAINT FK_CONTADOR_ID_ESCRITORIO_CONTABI_ESCRITORIO_CONTABILIDADE_ID FOREIGN KEY (ID_ESCRITORIO_CONTABILIDADE) REFERENCES ESCRITORIO_CONTABILIDADE(ID),
	PRIMARY KEY(ID)
);

ALTER TABLE CONDOMINIO ADD COLUMN ID_ESCRITORIO_CONTABILIDADE INTEGER;

INSERT INTO ESCRITORIO_CONTABILIDADE VALUES(DEFAULT,'J3 CONTAB','www.j3contab.com.br',NULL,NULL,0,1);

INSERT INTO GRUPO_USUARIO VALUES(DEFAULT,'ESCRITORIO_CONTABILIDADE');

UPDATE CONDOMINIO SET ID_ESCRITORIO_CONTABILIDADE = 1 WHERE ID = 20