CREATE TABLE IF NOT EXISTS DESPESAS(
	ID integer NOT NULL AUTO_INCREMENT,
	DESCRICAO varchar(250),
	VALOR double precision NOT NULL,
	MES_ANO_REFERENCIA date NOT NULL,	
	TIPO integer NOT NULL,
	ID_CONDOMINIO integer,
	ID_UNIDADE integer,
	CONSTRAINT FK_DESPESAS_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_DESPESAS_ID_UNIDADE_UNIDADE_ID FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TARIFA_GAS(
	ID integer NOT NULL AUTO_INCREMENT,	
	FATOR_CONVERSAO double precision NOT NULL,
	VALOR_COBRADO double precision NOT NULL,
	ID_CONDOMINIO integer NOT NULL,	
	CONSTRAINT FK_TARIFA_GAS_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),	
	CONSTRAINT UQ_TARIFA_GAS_ID_CONDOMINIO UNIQUE (ID_CONDOMINIO),
	PRIMARY KEY(ID)
);




