package br.com.condominiosvirtuais.util;

import br.com.condominiosvirtuais.entity.Agendamento;
import br.com.condominiosvirtuais.entity.Chamado;
import br.com.condominiosvirtuais.entity.Classificados;
import br.com.condominiosvirtuais.entity.Condomino;
import br.com.condominiosvirtuais.entity.MensagemRecebida;
import br.com.condominiosvirtuais.entity.Reserva;
import br.com.condominiosvirtuais.entity.Usuario;

/**
 * Classe utilitária criada para centralizar as mensagens que serão enviadas para os usuários por email
 * @author Maikel Joel de Souza
 */
public abstract class MensagensEmailUtil {
	
	private static final String LINK_CONDOMINIOS_VIRTUAIS = "<a href=\"http://www.condominiosvirtuais.com.br\" target=\"_blank\">www.condominiosvirtuais.com.br</a>";	
	
	private static final String SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS = "<a style=\"padding: 10px 8px 10px 0px; text-decoration: none;\" href=\"https://www.facebook.com/CondominiosVirtuais/\" target=\"_blank\"> <img id=\"facebook\" src=\"cid:facebook\" alt=\"facebook\"> </a>";
	
	private static final String SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS = "<a style=\"padding: 10px 8px 10px 0px; text-decoration: none;\" href=\"https://www.linkedin.com/company/condom%C3%ADnios-virtuais\" target=\"_blank\"> <img id=\"linkedin\" src=\"cid:linkedin\" alt=\"linkedin\"> </a>";
	
	private static final String SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS = "<a style=\"padding: 10px 8px 10px 0px; text-decoration: none;\" href=\"https://plus.google.com/+CondominiosvirtuaisBr\" target=\"_blank\"> <img id=\"Google Plus\" src=\"cid:googlePlus\" alt=\"Google Plus\"> </a>";
					
	
	public static String confirmacaoDeCadastro(Condomino condomino) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(condomino.getNome());
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.textoParte2"));		
		mensagem.append("<a ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A);
		mensagem.append(" href=\"http://www.condominiosvirtuais.com.br\" target=\"_blank\">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(".</span></a><br/>");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.textoParte3"));	
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.textoParte4"));
		mensagem.append("</span>");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.textoParte5"));
		mensagem.append("</p> <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.textoParte6"));
		mensagem.append(" ");
		mensagem.append(condomino.getEmail().getEmail());
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("msg.cadastroCondomino.textoParte7"));
		mensagem.append(" ");
		mensagem.append(condomino.getSenha());
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");		
		return mensagem.toString();
	}
	
	public static String solicitacaoDeMudanca(Agendamento agendamento, String nomeSindico) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(nomeSindico);
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getBloco().getNome());
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(String.valueOf(agendamento.getUnidade().getNumero()));
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(String.valueOf(agendamento.getCondomino().getNome()));
		mensagem.append(" </span>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte5"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), agendamento.getData()));
		mensagem.append(" </span>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte6"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraInicial());		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte7"));
		mensagem.append(" </span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte8"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraFinal());
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte7"));		
		mensagem.append(".</span></a><br/>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte9"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte10"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte11"));		
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte12"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte13"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();		
	}
	
	public static String solicitacaoDeMudancaComObservacao(Agendamento agendamento, String nomeSindico) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(nomeSindico);
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getBloco().getNome());
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(String.valueOf(agendamento.getUnidade().getNumero()));
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(String.valueOf(agendamento.getCondomino().getNome()));
		mensagem.append(" </span>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte5"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), agendamento.getData()));
		mensagem.append(" </span>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte6"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraInicial());		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte7"));
		mensagem.append(" </span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte8"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraFinal());
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte7"));		
		mensagem.append("</span>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte14"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getObservacao());
		mensagem.append("</span>.<br/>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte9"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte10"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte11"));		
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte12"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudança.textoParte13"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");		
		return mensagem.toString();		
	}
	
	public static String solicitacaoDeMudancaAprovada(Agendamento agendamento) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getCondomino().getNome());		
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), agendamento.getData()));
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraInicial());
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte8"));
		mensagem.append("</span> ");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraFinal());
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte8"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte5"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte6"));
		mensagem.append(" </span>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.aprovada.textoParte7"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");		
		return mensagem.toString();		
	}
	
	public static String solicitacaoDeMudancaReprovada(Agendamento agendamento) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getCondomino().getNome());		
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), agendamento.getData()));
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraInicial());
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte9"));
		mensagem.append("</span> ");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getHoraFinal());
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte9"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte5"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte6"));
		mensagem.append(" </span>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte7"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(agendamento.getMotivoReprovacao());
		mensagem.append(" </span><br/>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoMudanca.reprovada.textoParte8"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");		
		return mensagem.toString();		
	}
	
	public static String novaSenhaGerada(Usuario usuario, String novaSenha) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.usuarioNovaSenhaGerada.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.usuarioNovaSenhaGerada.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.usuarioNovaSenhaGerada.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(usuario.getNome());
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.usuarioNovaSenhaGerada.textoParte2"));
		mensagem.append("<br/> <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.usuarioNovaSenhaGerada.textoParte3"));
		mensagem.append(" ");
		mensagem.append(novaSenha);
		mensagem.append("</span></p>");		
		mensagem.append(AplicacaoUtil.i18n("msg.usuarioNovaSenhaGerada.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();		
	}
	
	public static String solicitacaoDeReserva(Reserva reserva, String nomeSindico) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(nomeSindico);
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getAmbiente().getNome());
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), reserva.getData()));
		mensagem.append("</span><br/>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String solicitacaoDeReservaAprovada(Reserva reserva) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getCondomino().getNome());
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getAmbiente().getNome());
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), reserva.getData()));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.textoParte5"));
		mensagem.append("</span><br/>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.aprovada.textoParte6"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String solicitacaoDeReservaReprovada(Reserva reserva) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getCondomino().getNome());
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getAmbiente().getNome());
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), reserva.getData()));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.textoParte5"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.textoParte6"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getMotivoReprovacao());
		mensagem.append("</span><br/>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.reprovada.textoParte7"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String mensagemRecebida(MensagemRecebida mensagemRecebida) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.mensagemRecebida.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.mensagemRecebida.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.mensagemRecebida.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(mensagemRecebida.getUsuarioDestinatario().getNome());
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.mensagemRecebida.textoParte2"));		
		mensagem.append("</span>.<br/>");		
		mensagem.append(AplicacaoUtil.i18n("msg.mensagemRecebida.textoParte3"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String fechamentoChamado(Chamado chamado, String nomeUsuario) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.assunto"));
		mensagem.append("</h1>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(nomeUsuario);
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(chamado.getNome());
		mensagem.append(" </span>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte3"));
		mensagem.append(".<br/>");		 
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String fechamentoChamadoComObservacao(Chamado chamado, String nomeUsuario) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.assunto"));
		mensagem.append("</h1>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(nomeUsuario);
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(chamado.getNome());
		mensagem.append(" </span>");		
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte5"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(chamado.getComentario());		
		mensagem.append("</span>.<br/>");		 
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.fechamento.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String aberturaChamado(Chamado chamado, String nomeSindico) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.abertura.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.abertura.assunto"));
		mensagem.append("</h1>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.abertura.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(nomeSindico);
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.abertura.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(chamado.getNome());
		mensagem.append("</span> <br/>");
		mensagem.append(AplicacaoUtil.i18n("msg.chamado.abertura.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String expiraClassificados(Classificados classificados, String nomeUsuario) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.expiraClassificados.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.expiraClassificados.assunto"));
		mensagem.append("</h1>");
		mensagem.append(AplicacaoUtil.i18n("msg.expiraClassificados.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(nomeUsuario);
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.expiraClassificados.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(classificados.getTitulo());
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.expiraClassificados.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), classificados.getDataExpira()));
		mensagem.append("</span> <br/>");
		mensagem.append(AplicacaoUtil.i18n("msg.expiraClassificados.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}
	
	public static String solicitacaoDeReservaSuspensa(Reserva reserva) throws InstantiationException, IllegalAccessException{		
		StringBuffer mensagem = new StringBuffer();
		mensagem.append("<html> <head lang=\"");
		mensagem.append(AplicacaoUtil.i18n("lang"));
		mensagem.append("\">");
		mensagem.append("<title>");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.assunto"));
		mensagem.append("</title>");
		mensagem.append("<meta charset=\"");
		mensagem.append(AplicacaoUtil.i18n("charset"));
		mensagem.append("\">");
		mensagem.append("</head>");
		mensagem.append("<body> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<figure>");
		mensagem.append("<img id=\"logoCabecalho\" src=\"cid:logo\" ");
		mensagem.append("alt=\"");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append("\">");
		mensagem.append("</figure>");
		mensagem.append("<h1 ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_H1);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.assunto"));
		mensagem.append("</h1>");
		mensagem.append("<p ");		
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);		
		mensagem.append(">");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.textoParte1"));
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getCondomino().getNome());
		mensagem.append("</span></p>");
		mensagem.append("<p ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_P);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.textoParte2"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getAmbiente().getNome());
		mensagem.append("</span>, ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.textoParte3"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.formatarData(AplicacaoUtil.i18n("formatoData"), reserva.getData()));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.textoParte4"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.textoParte5"));
		mensagem.append("</span> ");
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.textoParte6"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(reserva.getMotivoSuspensao());
		mensagem.append("</span><br/>");		
		mensagem.append(AplicacaoUtil.i18n("msg.solicitacaoReserva.suspensa.textoParte7"));
		mensagem.append(" <span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));
		mensagem.append("<br/><br/></span>");
		mensagem.append("<a  ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_A_BOTAO_ACESSAR_APLICACAO);
		mensagem.append(" href=\"http://app.condominiosvirtuais.com.br/CondominiosVirtuais/security/formLogin.xhtml\" target=\"_blank\">");
		mensagem.append(AplicacaoUtil.i18n("botaoAcessarAplicacao"));		
		mensagem.append("</a> <div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte1"));
		mensagem.append("</span><br/><br/>");
		mensagem.append("<span ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_SPAN);
		mensagem.append(">");
		mensagem.append(AplicacaoUtil.i18n("msg.rodapeEmailParte2"));
		mensagem.append(" - ");
		mensagem.append(LINK_CONDOMINIOS_VIRTUAIS);
		mensagem.append("<br/>");
		mensagem.append(AplicacaoUtil.i18n("emailContato"));
		mensagem.append("<br/></span>");
		mensagem.append("<div ");
		mensagem.append(CssMensagensEmailUtil.CSS_STYLE_DIV);
		mensagem.append(">");
		mensagem.append(SOCIAL_FACEBOOK_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_LINKEDIN_CONDOMINIOS_VIRTUAIS);
		mensagem.append(SOCIAL_GOOGLE_PLUS_CONDOMINIOS_VIRTUAIS);
		mensagem.append("</div></div></div></body></html>");	
		return mensagem.toString();
	}


}
