CREATE DATABASE condvirtuais;

CREATE SEQUENCE SEQ_CONDOMINIO START 1;

CREATE TABLE CONDOMINIO(
	ID integer default nextval('SEQ_CONDOMINIO') CONSTRAINT PK_CONDOMINIO PRIMARY KEY,
	NOME varchar(150) NOT NULL,
	SITUACAO integer NOT NULL	
);

CREATE SEQUENCE SEQ_ENDERECO START 1;

CREATE TABLE ENDERECO (
	ID integer default nextval('SEQ_ENDERECO') CONSTRAINT PK_ENDERECO PRIMARY KEY,
	ENDERECO varchar(100) NOT NULL,
	NUMERO integer,
	COMPLEMENTO varchar(150),
	CEP integer NOT NULL,
	BAIRRO varchar(100) NOT NULL,
	CIDADE varchar(100) NOT NULL,
	UF varchar(5) NOT NULL,
	PAIS varchar(20) NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_ID_ENDERECO_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID) 
);

CREATE SEQUENCE SEQ_BLOCO START 1;

CREATE TABLE BLOCO (
	ID integer default nextval('SEQ_BLOCO') CONSTRAINT PK_BLOCO PRIMARY KEY,
	NOME varchar(150) NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT UQ_NOME_ID_CONDOMINIO UNIQUE (NOME, ID_CONDOMINIO),
	CONSTRAINT FK_ID_BLOCO_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID)	
);

CREATE SEQUENCE SEQ_UNIDADE START 1;

CREATE TABLE UNIDADE (
	ID integer default nextval('SEQ_UNIDADE') CONSTRAINT PK_UNIDADE PRIMARY KEY,	
	TIPO integer NOT NULL,
	NUMERO integer NOT NULL,
	ID_BLOCO integer NOT NULL,
	CONSTRAINT UQ_NUMERO_ID_BLOCO UNIQUE (NUMERO, ID_BLOCO),
	CONSTRAINT FK_ID_UNIDADE_BLOCO FOREIGN KEY (ID_BLOCO) REFERENCES BLOCO(ID)
);

CREATE SEQUENCE SEQ_GRUPO_USUARIO START 1;

CREATE TABLE GRUPO_USUARIO (
	ID integer default nextval('SEQ_GRUPO_USUARIO') CONSTRAINT PK_GRUPO_USUARIO PRIMARY KEY,	
	NOME varchar(50) NOT NULL
);

CREATE SEQUENCE SEQ_USUARIO START 1;

CREATE TABLE USUARIO (
	ID integer default nextval('SEQ_USUARIO') CONSTRAINT PK_USUARIO PRIMARY KEY,	
	NOME varchar(150) NOT NULL,
	SENHA varchar(50) NOT NULL,
	SEXO integer,
	DATA_NASCIMENTO date,
	SITUACAO integer NOT NULL,
	ID_GRUPO_USUARIO integer NOT NULL,
	CONSTRAINT FK_ID_USUARIO_GRUPO_USUARIO FOREIGN KEY (ID_GRUPO_USUARIO) REFERENCES GRUPO_USUARIO(ID)
);


CREATE SEQUENCE SEQ_EMAIL_USUARIO START 1;

CREATE TABLE EMAIL_USUARIO (
	ID integer default nextval('SEQ_EMAIL_USUARIO') CONSTRAINT PK_EMAIL_USUARIO PRIMARY KEY,	
	EMAIL varchar(150) NOT NULL,
	PRINCIPAL boolean NOT NULL,
	ID_USUARIO integer NOT NULL,
	CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_PRINCIPAL_ID_USUARIO UNIQUE (PRINCIPAL, ID_USUARIO),
	CONSTRAINT FK_ID_EMAIL_USUARIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE SEQUENCE SEQ_USUARIO_CONDOMINIO START 1;

CREATE TABLE USUARIO_CONDOMINIO (
	ID integer default nextval('SEQ_USUARIO_CONDOMINIO') CONSTRAINT PK_USUARIO_CONDOMINIO PRIMARY KEY,	
	ID_USUARIO integer NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_ID_USUARIO_CONDOMINIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_ID_USUARIO_CONDOMINIO_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID)
);

CREATE SEQUENCE SEQ_CONDOMINO START 1;

CREATE TABLE CONDOMINO (
	ID integer default nextval('SEQ_CONDOMINO') CONSTRAINT PK_CONDOMINO PRIMARY KEY,	
	PROPRIETARIO boolean NOT NULL,
	TELEFONE_CELULAR bigint,
	TELEFONE_RESIDENCIAL bigint,
	TELEFONE_COMERCIAL bigint,	
	ID_UNIDADE integer NOT NULL,	
	CONSTRAINT FK_ID_CONDOMINO_UNIDADE FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	CONSTRAINT FK_ID_CONDOMINO_USUARIO FOREIGN KEY (ID) REFERENCES USUARIO(ID)
); 

CREATE SEQUENCE SEQ_GESTOR_CONDOMINIO START 1;

CREATE TABLE GESTOR_CONDOMINIO (
	ID integer default nextval('SEQ_GESTOR_CONDOMINIO') CONSTRAINT PK_GESTORES_CONDOMINIO PRIMARY KEY,
	ID_CONDOMINIO integer,
	ID_BLOCO integer,	
	ID_CONDOMINO integer NOT NULL,
	TIPO_CONDOMINO integer NOT NULL,
	CONSTRAINT FK_ID_GESTOR_CONDOMINIO_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_ID_GESTOR_CONDOMINIO_BLOCO FOREIGN KEY (ID_BLOCO) REFERENCES BLOCO(ID),
	CONSTRAINT FK_ID_GESTOR_CONDOMINIO_CONDOMINO FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID)
);

CREATE SEQUENCE SEQ_CONJUNTO_BLOCO START 1;

CREATE TABLE CONJUNTO_BLOCO (
	ID integer default nextval('SEQ_CONJUNTO_BLOCO') CONSTRAINT PK_CONJUNTO_BLOCO PRIMARY KEY,	
	tipo integer NOT NULL	
);

CREATE SEQUENCE SEQ_BLOCO_CONJUNTO_BLOCO START 1;

CREATE TABLE BLOCO_CONJUNTO_BLOCO (
	ID integer default nextval('SEQ_BLOCO_CONJUNTO_BLOCO') CONSTRAINT PK_BLOCO_CONJUNTO_BLOCO PRIMARY KEY,
	ID_BLOCO integer NOT NULL,
	ID_CONJUNTO_BLOCO integer NOT NULL,
	CONSTRAINT FK_ID_BLOCO_CONJUNTO_BLOCO_BLOCO FOREIGN KEY (ID_BLOCO) REFERENCES BLOCO(ID),
	CONSTRAINT FK_ID_BLOCO_CONJUNTO_BLOCO_CONJUNTO_BLOCO FOREIGN KEY (ID_CONJUNTO_BLOCO) REFERENCES CONJUNTO_BLOCO(ID)
);

CREATE SEQUENCE SEQ_AMBIENTE START 1;

CREATE TABLE AMBIENTE (
	ID integer default nextval('SEQ_AMBIENTE') CONSTRAINT PK_AMBIENTE PRIMARY KEY,
	NOME varchar(50) NOT NULL,
	ID_CONDOMINIO integer,
	ID_CONJUNTO_BLOCO integer,
	CONSTRAINT FK_ID_AMBIENTE_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_ID_AMBIENTE_CONJUNTO_BLOCO FOREIGN KEY (ID_CONJUNTO_BLOCO) REFERENCES CONJUNTO_BLOCO(ID)
);

CREATE SEQUENCE SEQ_ITEM_AMBIENTE START 1;

CREATE TABLE ITEM_AMBIENTE (
	ID integer default nextval('SEQ_ITEM_AMBIENTE') CONSTRAINT PK_ITEM_AMBIENTE PRIMARY KEY,
	NOME varchar(50) NOT NULL,
	QUANTIDADE integer NOT NULL,
	ID_AMBIENTE integer NOT NULL,	
	CONSTRAINT FK_ID_ITEM_AMBIENTE_AMBIENTE FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE(ID)
);

CREATE TABLE FUNCIONARIO (
	ID integer CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,	
	FUNCAO varchar(50) NOT NULL,
	TELEFONE_CELULAR bigint,
	TELEFONE_RESIDENCIAL bigint,	
	ID_CONDOMINIO integer,
	ID_CONJUNTO_BLOCO integer,
	CONSTRAINT FK_ID_FUNCIONARIO_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_ID_FUNCIONARIO_CONJUNTO_BLOCO FOREIGN KEY (ID_CONJUNTO_BLOCO) REFERENCES CONJUNTO_BLOCO(ID),	
	CONSTRAINT FK_ID_FUNCIONARIO_USUARIO FOREIGN KEY (ID) REFERENCES USUARIO(ID)
);

CREATE SEQUENCE SEQ_RESERVA START 1;

CREATE TABLE RESERVA (
	ID integer default nextval('SEQ_RESERVA') CONSTRAINT PK_RESERVA PRIMARY KEY,
	ID_CONDOMINO integer NOT NULL,
	ID_AMBIENTE integer NOT NULL,
	SITUACAO varchar(30) NOT NULL,
	MOTIVO_REPROVACAO varchar(150),
	DATA date NOT NULL,
	CONSTRAINT UQ_DATA_ID_AMBIENTE UNIQUE (DATA, ID_AMBIENTE),
	CONSTRAINT FK_ID_RESERVA_CONDOMINO FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),
	CONSTRAINT FK_ID_RESERVA_AMBIENTE FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE(ID)	
);

CREATE SEQUENCE SEQ_MENSAGEM_RECEBIDA START 1;

CREATE TABLE MENSAGEM_RECEBIDA (
	ID integer default nextval('SEQ_MENSAGEM_RECEBIDA') CONSTRAINT PK_MENSAGEM_RECEBIDA PRIMARY KEY,
	ID_USUARIO_REMETENTE integer NOT NULL,
	ID_USUARIO_DESTINATARIO integer NOT NULL,
	VISUALIZADA boolean NOT NULL,
	DATA date NOT NULL,
	ASSUNTO varchar(50) NOT NULL,
	TEXTO text NOT NULL,
	CONSTRAINT FK_ID_MENSAGEM_REM_USUARIO FOREIGN KEY (ID_USUARIO_REMETENTE) REFERENCES USUARIO(ID),
	CONSTRAINT FK_ID_MENSAGEM_DES_USUARIO FOREIGN KEY (ID_USUARIO_DESTINATARIO) REFERENCES USUARIO(ID)	
);

CREATE SEQUENCE SEQ_MENSAGEM_ENVIADA START 1;

CREATE TABLE MENSAGEM_ENVIADA (
	ID integer default nextval('SEQ_MENSAGEM_ENVIADA') CONSTRAINT PK_MENSAGEM_ENVIADA PRIMARY KEY,
	ID_USUARIO_REMETENTE integer NOT NULL,
	DATA date NOT NULL,
	ASSUNTO varchar(50) NOT NULL,
	TEXTO text NOT NULL,
	CONSTRAINT FK_ID_MENSAGEM_REM_USUARIO FOREIGN KEY (ID_USUARIO_REMETENTE) REFERENCES USUARIO(ID)	
);

CREATE SEQUENCE SEQ_USUARIOS_RECEBIDOS_MENSAGEM START 1;

CREATE TABLE USUARIOS_RECEBIDOS_MENSAGEM (
	ID integer default nextval('SEQ_USUARIOS_RECEBIDOS_MENSAGEM') CONSTRAINT PK_SEQ_USUARIOS_RECEBIDOS_MENSAGEM PRIMARY KEY,
	ID_USUARIO integer NOT NULL,
	ID_MENSAGEM_ENVIADA integer NOT NULL,
	CONSTRAINT FK_ID_USUARIO_RECE_MENSAGEM_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_ID_USUARIO_RECE_MENSAGEM_MSG_ENVIADA FOREIGN KEY (ID_MENSAGEM_ENVIADA) REFERENCES MENSAGEM_ENVIADA(ID)
);

CREATE TABLE CONFIGURACAO_APLICACAO (
	CHAVE varchar(50) NOT NULL,
	VALOR varchar(250) NOT NULL,	
	CONSTRAINT UQ_CHAVE UNIQUE (CHAVE)		
);

CREATE SEQUENCE SEQ_EMAIL START 1;

CREATE TABLE EMAIL (
	ID integer default nextval('SEQ_EMAIL') CONSTRAINT PK_EMAIL PRIMARY KEY,
	DE varchar(100),
	PARA text NOT NULL,
	CC text,
	CO text,
	ASSUNTO varchar(50) NOT NULL,
	MENSAGEM text NOT NULL
);

CREATE SEQUENCE SEQ_CLASSIFICADOS START 1;

CREATE TABLE CLASSIFICADOS (
	ID integer default nextval('SEQ_CLASSIFICADOS') CONSTRAINT PK_CLASSIFICADOS PRIMARY KEY,	
	TITULO varchar(100) NOT NULL,
	DESCRICAO varchar(350),
	TELEFONE1 bigint NOT NULL,
	TELEFONE2 bigint,
	VALOR double precision,
	DATA_EXPIRA date NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	ID_USUARIO integer NOT NULL,
	CONSTRAINT FK_ID_CLASSIFICADOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_ID_CLASSIFICADOS_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID)	
);


CREATE SEQUENCE SEQ_ARQUIVO START 1;

CREATE TABLE ARQUIVO (
	ID integer default nextval('SEQ_ARQUIVO') CONSTRAINT PK_ARQUIVO PRIMARY KEY,	
	ID_USUARIO integer,
	ID_CONDOMINIO integer,
	ID_AMBIENTE integer,
	ID_CLASSIFICADOS integer,
	NOME varchar(100) NOT NULL,
	MIME_TYPE varchar(100) NOT NULL,
	CONSTRAINT FK_ID_CLASSIFICADOS_USUARIO FOREIGN KEY (ID_CLASSIFICADOS) REFERENCES CLASSIFICADOS(ID),
	CONSTRAINT FK_ID_ARQUIVO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_ID_ARQUIVO_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_ID_ARQUIVO_AMBIENTE FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE(ID)
);

CREATE SEQUENCE SEQ_TELEFONES_UTEIS START 1;

CREATE TABLE TELEFONES_UTEIS (
	ID integer default nextval('SEQ_TELEFONES_UTEIS') CONSTRAINT PK_TELEFONES_UTEIS PRIMARY KEY,	
	NOME varchar(150) NOT NULL,
	TELEFONE1 bigint NOT NULL,
	TELEFONE2 bigint,
	EMAIL varchar(150),
	SITE varchar(150),
	DESCRICAO varchar(350),
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_ID_TELEFONES_UTEIS_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID)	
);

CREATE SEQUENCE SEQ_ENQUETE START 1;

CREATE TABLE ENQUETE (
	ID integer default nextval('SEQ_ENQUETE') CONSTRAINT PK_ENQUETE PRIMARY KEY,	
	DATA_FIM date NOT NULL,
	DATA_CRIACAO date NOT NULL,
	PERGUNTA varchar(150) NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_ID_ENQUETE_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID)	
);

CREATE SEQUENCE SEQ_ALTERNATIVA_ENQUETE START 1;

CREATE TABLE ALTERNATIVA_ENQUETE (
	ID integer default nextval('SEQ_ALTERNATIVA_ENQUETE') CONSTRAINT PK_ALTERNATIVA_ENQUETE PRIMARY KEY,	
	ALTERNATIVA varchar(150) NOT NULL,
	VOTO integer NOT NULL,	
	ID_ENQUETE integer NOT NULL,
	CONSTRAINT FK_ID_ALTERNATIVA_ENQUETE_ENQUETE FOREIGN KEY (ID_ENQUETE) REFERENCES ENQUETE(ID)	
);


CREATE TABLE VOTO_ENQUETE (		
	ID_UNIDADE integer NOT NULL,
	ID_ENQUETE integer NOT NULL,
	CONSTRAINT UQ_ID_VOTO_ID_ENQUETE UNIQUE (ID_UNIDADE, ID_ENQUETE),
	CONSTRAINT FK_ID_VOTO_ENQUETE_UNIDADE FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	CONSTRAINT FK_ID_VOTO_ENQUETE_ENQUETE FOREIGN KEY (ID_ENQUETE) REFERENCES ENQUETE(ID)
);

CREATE SEQUENCE SEQ_GARAGEM START 1;

CREATE TABLE GARAGEM(
	ID integer default nextval('SEQ_GARAGEM') CONSTRAINT PK_GARAGEM PRIMARY KEY,
	TAMANHO integer NOT NULL,
	NUMERO varchar(10) NOT NULL,
	ID_UNIDADE integer NOT NULL,	
	CONSTRAINT FK_ID_GARAGEM_UNIDADE FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID)	
);

CREATE SEQUENCE SEQ_VEICULO START 1;

CREATE TABLE VEICULO(
	ID integer default nextval('SEQ_VEICULO') CONSTRAINT PK_VEICULO PRIMARY KEY,
	NOME varchar(50) NOT NULL,
	PLACA varchar(30) NOT NULL,
	TAMANHO integer NOT NULL,
	TIPO integer NOT NULL,	
	ID_CONDOMINO integer NOT NULL,
	ID_GARAGEM integer,
	CONSTRAINT UQ_ID_PLACA UNIQUE (PLACA),
	CONSTRAINT FK_ID_VEICULO_CONDOMINO FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),
	CONSTRAINT FK_ID_VEICULO_GARAGEM FOREIGN KEY (ID_GARAGEM) REFERENCES GARAGEM(ID)
);




