INSERT INTO GRUPO_USUARIO (NOME) VALUES ('ADMINISTRADOR');
INSERT INTO GRUPO_USUARIO (NOME) VALUES ('ADMINISTRADORA');
INSERT INTO GRUPO_USUARIO (NOME) VALUES ('SINDICO_PROFISSIONAL');
INSERT INTO GRUPO_USUARIO (NOME) VALUES ('SINDICO');
INSERT INTO GRUPO_USUARIO (NOME) VALUES ('CONDOMINO');
INSERT INTO GRUPO_USUARIO (NOME) VALUES ('FUNCIONARIO');

-- Senha xpto73
INSERT INTO USUARIO (NOME,SENHA,SEXO,DATA_NASCIMENTO,SITUACAO,ID_GRUPO_USUARIO) VALUES ('ADMIN','2376d916fa41045994dd9ca141ca0a9f',0,NULL,1,(SELECT ID FROM GRUPO_USUARIO WHERE NOME = 'ADMINISTRADOR'));


INSERT INTO EMAIL_USUARIO (EMAIL,PRINCIPAL,ID_USUARIO) VALUES ('maikel.souza@gmail.com',true,(SELECT ID FROM USUARIO WHERE NOME = 'ADMIN'));

INSERT INTO CONFIGURACAO_APLICACAO VALUES ('protocolo_email','smtp');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('protocolo_email_security','smtps');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('host_email','smtp.gmail.com');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('usuario_email','contato@condominiosvirtuais.com.br');

INSERT INTO CONFIGURACAO_APLICACAO VALUES ('mail.smtp.auth','true');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('mail.smtp.port','465');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('qtd_envio_email_lote','10');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('senha_email','mkl86233');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('endereco_arquivos','D://Condominios Virtuais/arquivos');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('endereco_email_admin_aplicacao','contato@condominiosvirtuais.com.br');


