INSERT INTO GRUPO_USUARIO VALUES (NEXTVAL('SEQ_GRUPO_USUARIO'),'ADMINISTRADOR');
INSERT INTO GRUPO_USUARIO VALUES (NEXTVAL('SEQ_GRUPO_USUARIO'),'ADMINISTRADORA');
INSERT INTO GRUPO_USUARIO VALUES (NEXTVAL('SEQ_GRUPO_USUARIO'),'SINDICO_PROFISSIONAL');
INSERT INTO GRUPO_USUARIO VALUES (NEXTVAL('SEQ_GRUPO_USUARIO'),'SINDICO');
INSERT INTO GRUPO_USUARIO VALUES (NEXTVAL('SEQ_GRUPO_USUARIO'),'CONDOMINO');
INSERT INTO GRUPO_USUARIO VALUES (NEXTVAL('SEQ_GRUPO_USUARIO'),'FUNCIONARIO');

INSERT INTO USUARIO(VALUES (NEXTVAL('SEQ_USUARIO'),'ADMIN','ADMIN',1,NULL,1,(SELECT ID FROM GRUPO_USUARIO WHERE NOME = 'ADMINISTRADOR')));
INSERT INTO EMAIL_USUARIO(VALUES (NEXTVAL('SEQ_EMAIL_USUARIO'),'maikel.souza@gmail.com',true,(SELECT ID FROM USUARIO WHERE NOME = 'ADMIN')));

INSERT INTO CONFIGURACAO_APLICACAO VALUES ('protocolo_email','smtp');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('protocolo_email_security','smtps');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('host_email','smtp.gmail.com');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('usuario_email','maikel.souza@gmail.com');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('senha_email','abc');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('mail.smtp.auth','true');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('mail.smtp.port','465');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('qtd_envio_email_lote','10');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('endereco_arquivos',E'D:\\Maikel\\Outros\\Ideias\\Gerenciador de Condominios\\Projeto\\arquivos');
INSERT INTO CONFIGURACAO_APLICACAO VALUES ('endereco_email_admin_aplicacao','maikel.souza@gmail.com');





