CREATE DATABASE condvirtuais;

CREATE TABLE IF NOT EXISTS CONDOMINIO(
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(150) NOT NULL,
	SITUACAO integer NOT NULL,
	CNPJ BIGINT NOT NULL,
	TELEFONE_CELULAR BIGINT,
	TELEFONE_FIXO BIGINT,
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS ENDERECO (
	ID integer NOT NULL AUTO_INCREMENT,
	ENDERECO varchar(100) NOT NULL,
	NUMERO integer,
	COMPLEMENTO varchar(150),
	CEP integer NOT NULL,
	BAIRRO varchar(100) NOT NULL,
	CIDADE varchar(100) NOT NULL,
	UF varchar(5) NOT NULL,
	PAIS varchar(20) NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_ENDERECO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS BLOCO (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(150) NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT UQ_BLOCO_NOME_ID_CONDOMINIO UNIQUE (NOME, ID_CONDOMINIO),
	CONSTRAINT FK_BLOCO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS UNIDADE (
	ID integer NOT NULL AUTO_INCREMENT,	
	TIPO integer NOT NULL,
	NUMERO integer NOT NULL,
	ID_BLOCO integer NOT NULL,
	CONSTRAINT UQ_UNIDADE_NUMERO_ID_BLOCO UNIQUE (NUMERO, ID_BLOCO),
	CONSTRAINT FK_UNIDADE_ID_BLOCO_BLOCO_ID FOREIGN KEY (ID_BLOCO) REFERENCES BLOCO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS GRUPO_USUARIO (
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(50) NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS USUARIO (
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150) NOT NULL,
	SENHA varchar(50) NOT NULL,
	SEXO integer,
	DATA_NASCIMENTO date,
	SITUACAO integer NOT NULL,
	ULTIMO_LOGIN DATETIME,
	ULTIMO_LOGOUT DATETIME,
	ID_GRUPO_USUARIO integer NOT NULL,
	CONSTRAINT FK_USUARIO_ID_GRUPO_USUARIO_GRUPO_USUARIO_ID FOREIGN KEY (ID_GRUPO_USUARIO) REFERENCES GRUPO_USUARIO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS EMAIL_USUARIO (
	ID integer NOT NULL AUTO_INCREMENT,	
	EMAIL varchar(150) NOT NULL,
	PRINCIPAL boolean NOT NULL,
	ID_USUARIO integer NOT NULL,
	CONSTRAINT UQ_EMAIL_USUARIO_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_EMAIL_USUARIO_PRINCIPAL_ID_USUARIO UNIQUE (PRINCIPAL, ID_USUARIO),
	CONSTRAINT FK_EMAIL_USUARIO_ID_USUARIO_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS USUARIO_CONDOMINIO (
	ID integer NOT NULL AUTO_INCREMENT,	
	ID_USUARIO integer NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_USUARIO_CONDOMINIO_ID_USUARIO_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_USUARIO_CONDOMINIO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CONDOMINO (
	ID integer NOT NULL AUTO_INCREMENT,	
	PROPRIETARIO boolean NOT NULL,
	TELEFONE_CELULAR bigint,
	TELEFONE_RESIDENCIAL bigint,
	TELEFONE_COMERCIAL bigint,	
	ID_UNIDADE integer NOT NULL,	
	CONSTRAINT FK_CONDOMINO_ID_UNIDADE_UNIDADE_ID FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	CONSTRAINT FK_CONDOMINO_ID_USUARIO_ID FOREIGN KEY (ID) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
); 

CREATE TABLE IF NOT EXISTS GESTOR_CONDOMINIO (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_CONDOMINIO integer,
	ID_BLOCO integer,	
	ID_CONDOMINO integer NOT NULL,
	TIPO_CONDOMINO integer NOT NULL,
	CONSTRAINT FK_GESTOR_CONDOMINIO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_GESTOR_CONDOMINIO_ID_BLOCO_BLOCO_ID FOREIGN KEY (ID_BLOCO) REFERENCES BLOCO(ID),
	CONSTRAINT FK_GESTOR_CONDOMINIO_ID_CONDOMINO_CONDOMINO_ID FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS CONJUNTO_BLOCO (
	ID integer NOT NULL AUTO_INCREMENT,	
	TIPO integer NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS BLOCO_CONJUNTO_BLOCO (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_BLOCO integer NOT NULL,
	ID_CONJUNTO_BLOCO integer NOT NULL,
	CONSTRAINT FK_BLOCO_CONJUNTO_BLOCO_ID_BLOCO_BLOCO_ID FOREIGN KEY (ID_BLOCO) REFERENCES BLOCO(ID),
	CONSTRAINT FK_BLOCO_CONJUNTO_BLOCO_ID_CONJUNTO_BLOCO_CONJUNTO_BLOCO_UD FOREIGN KEY (ID_CONJUNTO_BLOCO) REFERENCES CONJUNTO_BLOCO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS AMBIENTE (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(50) NOT NULL,
	ID_CONDOMINIO integer,
	ID_CONJUNTO_BLOCO integer,
	CONSTRAINT FK_AMBIENTE_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_AMBIENTE_ID_CONJUNTO_BLOCO_BLOCO_ID FOREIGN KEY (ID_CONJUNTO_BLOCO) REFERENCES CONJUNTO_BLOCO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ITEM_AMBIENTE (
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(50) NOT NULL,
	QUANTIDADE integer NOT NULL,
	ID_AMBIENTE integer NOT NULL,	
	CONSTRAINT FK_ITEM_AMBIENTE_ID_AMBIENTE_AMBIENTE_ID FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
	ID integer NOT NULL AUTO_INCREMENT,
	FUNCAO varchar(50) NOT NULL,
	TELEFONE_CELULAR bigint,
	TELEFONE_RESIDENCIAL bigint,	
	ID_CONDOMINIO integer,
	ID_CONJUNTO_BLOCO integer,
	CONSTRAINT FK_FUNCIONARIO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_FUNCIONARIO_ID_CONJUNTO_BLOCO_CONJUNTO_BLOCO_ID FOREIGN KEY (ID_CONJUNTO_BLOCO) REFERENCES CONJUNTO_BLOCO(ID),	
	CONSTRAINT FK_FUNCIONARIO_ID_USUARIO_ID FOREIGN KEY (ID) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS RESERVA (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_CONDOMINO integer NOT NULL,
	ID_AMBIENTE integer NOT NULL,
	SITUACAO varchar(30) NOT NULL,
	MOTIVO_REPROVACAO varchar(150),
	DATA date NOT NULL,
	CONSTRAINT FK_RESERVA_ID_CONDOMINO_CONDOMINO_ID FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),
	CONSTRAINT FK_RESERVA_ID_AMBIENTE_AMBIENTE_ID FOREIGN KEY (ID_AMBIENTE) REFERENCES AMBIENTE(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS MENSAGEM_RECEBIDA (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_USUARIO_REMETENTE integer NOT NULL,
	ID_USUARIO_DESTINATARIO integer NOT NULL,
	VISUALIZADA boolean NOT NULL,
	DATA timestamp NOT NULL,
	ASSUNTO varchar(50) NOT NULL,
	TEXTO text NOT NULL,
	CONSTRAINT FK_MENSAGEM_RECEBIDA_ID_USUARIO_REMETENTE_USUARIO_ID FOREIGN KEY (ID_USUARIO_REMETENTE) REFERENCES USUARIO(ID),
	CONSTRAINT FK_MENSAGEM_RECEBIDA_ID_USUARIO_DESTINATARIO_USUARIO_ID FOREIGN KEY (ID_USUARIO_DESTINATARIO) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS MENSAGEM_ENVIADA (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_USUARIO_REMETENTE integer NOT NULL,
	DATA timestamp NOT NULL,
	ASSUNTO varchar(50) NOT NULL,
	TEXTO text NOT NULL,
	CONSTRAINT FK_MENSAGEM_ENVIADA_ID_USUARIO_REMETENTE_USUARIO_ID FOREIGN KEY (ID_USUARIO_REMETENTE) REFERENCES USUARIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS USUARIOS_RECEBIDOS_MENSAGEM (
	ID integer NOT NULL AUTO_INCREMENT,
	ID_USUARIO integer NOT NULL,
	ID_MENSAGEM_ENVIADA integer NOT NULL,
	CONSTRAINT FK_USU_RECEBI_MENSAGEM_ID_USUARIO_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_USU_RECEBI_MENSAGEM_ID_MENSAGEM_ENVIADA_MENSAGEM_ENVIADA_ID FOREIGN KEY (ID_MENSAGEM_ENVIADA) REFERENCES MENSAGEM_ENVIADA(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CONFIGURACAO_APLICACAO (
	CHAVE varchar(50) NOT NULL,
	VALOR varchar(250) NOT NULL,	
	CONSTRAINT UQ_CONFIGURACAO_APLICACAO_CHAVE UNIQUE (CHAVE)		
);


CREATE TABLE IF NOT EXISTS EMAIL (
	ID integer NOT NULL AUTO_INCREMENT,
	DE varchar(100),
	PARA text NOT NULL,
	CC text,
	CO text,
	ASSUNTO varchar(100) NOT NULL,
	MENSAGEM text NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS CLASSIFICADOS (
	ID integer NOT NULL AUTO_INCREMENT,	
	TITULO varchar(100) NOT NULL,
	DESCRICAO varchar(350),
	TELEFONE1 bigint NOT NULL,
	TELEFONE2 bigint,
	VALOR double precision,
	DATA_EXPIRA date NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	ID_USUARIO integer NOT NULL,
	CONSTRAINT FK_CLASSIFICADOS_ID_USUARIO_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_CLASSIFICADOS_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS ARQUIVO (
	ID integer NOT NULL AUTO_INCREMENT,	
	ID_USUARIO integer,
	ID_CONDOMINIO integer,
	ID_CLASSIFICADOS integer,
	NOME varchar(100) NOT NULL,
	MIME_TYPE varchar(100) NOT NULL,
	CONSTRAINT FK_ARQUIVO_ID_CLASSIFICADOS_CLASSIFICADOS_ID FOREIGN KEY (ID_CLASSIFICADOS) REFERENCES CLASSIFICADOS(ID),
	CONSTRAINT FK_ARQUIVO_ID_USUARIO_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT FK_ARQUIVO_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS TELEFONES_UTEIS (
	ID integer NOT NULL AUTO_INCREMENT,	
	NOME varchar(150) NOT NULL,
	TELEFONE1 bigint NOT NULL,
	TELEFONE2 bigint,
	EMAIL varchar(150),
	SITE varchar(150),
	DESCRICAO varchar(350),
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_TELEFONES_UTEIS_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ENQUETE (
	ID integer NOT NULL AUTO_INCREMENT,	
	DATA_FIM date NOT NULL,
	DATA_CRIACAO date NOT NULL,
	PERGUNTA varchar(150) NOT NULL,
	ID_CONDOMINIO integer NOT NULL,
	CONSTRAINT FK_ENQUETE_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS ALTERNATIVA_ENQUETE (
	ID integer NOT NULL AUTO_INCREMENT,	
	ALTERNATIVA varchar(150) NOT NULL,
	VOTO integer NOT NULL,	
	ID_ENQUETE integer NOT NULL,
	CONSTRAINT FK_ALTERNATIVA_ENQUETE_ID_ENQUETE_ENQUETE_ID FOREIGN KEY (ID_ENQUETE) REFERENCES ENQUETE(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS VOTO_ENQUETE (		
	ID_UNIDADE integer NOT NULL,
	ID_ENQUETE integer NOT NULL,	
	CONSTRAINT UQ_VOTO_ENQUETE_ID_UNIDADE_ID_ENQUETE UNIQUE (ID_UNIDADE, ID_ENQUETE),    
	CONSTRAINT FK_VOTO_ENQUETE_ID_UNIDADE_UNIDADE_ID FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	CONSTRAINT FK_VOTO_ENQUETE_ID_ENQUETE_ENQUETE_ID FOREIGN KEY (ID_ENQUETE) REFERENCES ENQUETE(ID)
);


CREATE TABLE IF NOT EXISTS GARAGEM(
	ID integer NOT NULL AUTO_INCREMENT,
	TAMANHO integer NOT NULL,
	NUMERO varchar(10) NOT NULL,
	ID_UNIDADE integer NOT NULL,	
	CONSTRAINT FK_GARAGEM_ID_UNIDADE_UNIDADE_ID FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS VEICULO(
	ID integer NOT NULL AUTO_INCREMENT,
	NOME varchar(50) NOT NULL,
	PLACA varchar(30) NOT NULL,
	TAMANHO integer NOT NULL,
	TIPO integer NOT NULL,	
	ID_CONDOMINO integer NOT NULL,
	ID_GARAGEM integer,
	CONSTRAINT UQ_VEICULO_PLACA UNIQUE (PLACA),
	CONSTRAINT FK_VEICULO_ID_CONDOMINO_CONDOMINO_ID FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),
	CONSTRAINT FK_VEICULO_ID_GARAGEM_GARAGEM_ID FOREIGN KEY (ID_GARAGEM) REFERENCES GARAGEM(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS AGENDAMENTO(
	ID integer NOT NULL AUTO_INCREMENT,
	DATA date NOT NULL,
	HORA_INICIAL varchar(10) NOT NULL,
	HORA_FINAL varchar(10) NOT NULL,
	OBSERVACAO varchar(200),
	SITUACAO varchar(30) NOT NULL,
	MOTIVO_REPROVACAO varchar(150),
	ID_CONDOMINO integer NOT NULL,
	CONSTRAINT FK_AGENDAMENTO_ID_CONDOMINO_CONDOMINO_ID FOREIGN KEY (ID_CONDOMINO) REFERENCES CONDOMINO(ID),	
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS DESPESAS(
	ID integer NOT NULL AUTO_INCREMENT,
	DESCRICAO varchar(250),
	VALOR double precision NOT NULL,
	MES_ANO_REFERENCIA date NOT NULL,	
	TIPO integer NOT NULL,
	ID_CONDOMINIO integer,
	ID_UNIDADE integer,
	CONSTRAINT FK_DESPESAS_ID_CONDOMINIO_CONDOMINIO_ID FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO(ID),
	CONSTRAINT FK_DESPESAS_ID_UNIDADE_UNIDADE_ID FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID),
	PRIMARY KEY(ID)
);


